# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               깃한광종
tagline:             ' Getting better every single moment'
description:         '데이터 수집부터 분석,시각화까지'
url:                 https://github.com/GWANGJONGHAN
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              GWANGJONG HAN
  url:               http://www.facebook.com/gwangjonghan
  email:             kj0225486@gmail.com

# Custom vars
version:             1.0.0

##_config.yml 수정
#https://hoisharka.github.io/jekyll/2017/12/03/jekyll-category-001/
category_dir: category/
tag_dir: tag/